/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    BottomActionBar: typeof import('./src/components/BottomActionBar.vue')['default']
    ChatBubble: typeof import('./src/components/ChatBubble.vue')['default']
    ConversationListItem: typeof import('./src/components/ConversationListItem.vue')['default']
    DetailHero: typeof import('./src/components/DetailHero.vue')['default']
    MatchReasonsBlock: typeof import('./src/components/MatchReasonsBlock.vue')['default']
    PromptAnswerBlock: typeof import('./src/components/PromptAnswerBlock.vue')['default']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    UserCard: typeof import('./src/components/UserCard.vue')['default']
  }
}
